name: Send Information to Workflow

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'components-info/*.json'
env:
  mascot: pepe

jobs:
  get-json-files:
    runs-on: ubuntu-latest
    env:
      ORG_SECRET: ${{secrets.ORG_SECRET}}
    outputs:
      json-data: ${{ steps.get-json-files.outputs.JSON_DATA }}
      misecretito: ${{ steps.devolvertoken.outputs.MI_TOKEN }}
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
            path: './'
      - name: Get JSON files
        id: get-json-files
        run: |
          echo "the secret is ..."
          echo $ORG_SECRET
          echo "the secret with brackets is..."
          echo ${{secrets.ORG_SECRET}}
          echo "MI_TOKEN=$ORG_SECRET"
          cd './components-info'
          jq -s '.' *.json > joined.json
          echo "JSON_DATA=$(jq -c . < joined.json)" >> $GITHUB_OUTPUT
      - name: Devolver token si dios quiere
        id: devolvertoken
        run: echo "MI_TOKEN=$ORG_SECRET" >> $GITHUB_OUTPUT
  call-workflow-passing-data:
    needs: get-json-files
    strategy:
      matrix:
        json: ${{ fromJson(needs.get-json-files.outputs.json-data) }}
    permissions:
      contents: read
      pull-requests: write
    uses: DCodingJLD/pruebawebhook1/.github/workflows/workflow-to-components.yml@main
    with:
      repo:  ${{ github.repository }}
      name:  ${{ matrix.json.name }}
      file:  ${{ toJSON(matrix.json) }}
#    secrets:
#      token: ${{secrets.ORG_SECRET}}
          
