name: Send Information to Workflow

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'components-info/*.json'
env:
  mascot: Mona

jobs:
  get-json-files:
    runs-on: ubuntu-latest
    env:
      COMPONENTS_API_TOKEN: ${{secrets.COMPONENTS_API_TOKEN}}
    outputs:
      json-data: ${{ steps.get-json-files.outputs.JSON_DATA }}
      secret: ${{ secrets.COMPONENTS_API_TOKEN }}
      misecretito: $secret
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with:
            path: './'
      - name: Get JSON files
        id: get-json-files
        run: |
          echo "the secret is ..."
          echo $COMPONENTS_API_TOKEN
          echo "the secret with brackets is..."
          echo ${{secrets.COMPONENTS_API_TOKEN}}
          cd './components-info'
          jq -s '.' *.json > joined.json
          echo "JSON_DATA=$(jq -c . < joined.json)" >> $GITHUB_OUTPUT
  call-workflow-passing-data:
    needs: get-json-files
    strategy:
      matrix:
        json: ${{ fromJson(needs.get-json-files.outputs.json-data) }}
    permissions:
      contents: read
      pull-requests: write
    uses: DCodingJLD/pruebawebhook1/.github/workflows/workflow-to-components.yml@main
    with:
      repo:  ${{ github.repository }}
      name:  ${{ matrix.json.name }}
      file:  ${{ toJSON(matrix.json) }}
      token: ${{ needs.get-json-files.outputs.misecretito }}
          
