name: Workflow that webhooks to components
on:
  workflow_call:
    inputs:
      repo:
        description: 'The github repository that is sending information'
        required: false
        type: string
      name:
        required: false
        type: string
        default: 'component'
      file:
        required: false
        type: string
      is_pr:
        required: false
        type: string
    secrets:
      token:
        required: false

jobs:
  triage:
    runs-on: ubuntu-latest
    env:
      repo: ${{ inputs.repo }}
      name: ${{ inputs.name }}
      file: ${{ inputs.file }}
      is_pr: ${{ inputs.is_pr }}
      COMPONENTS_GHA_JSON_TOKEN: ${{secrets.token}}
    steps:
      - name: Check out repo's default branch
        uses: actions/checkout@v3
      - name: Check out el otro
        uses: actions/checkout@v3
        with:
          repository: DCodingJLD/pruebawebhook1
          path: my-tools
          token: ${{ github.token }}
      - name: listar nuevo repo
        run: |
          cd ..
          ls -all
          cd my-tools
          ls -all
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - run: go version
      - name: printing out the parsed information
        run: |
          echo "The repo that is sending the information is : $repo" 
          echo "The name of the component is : $name"
          echo "The json is : $file"
          echo "The is_pr is : $is_pr"
          echo "the token is : $COMPONENTS_GHA_JSON_TOKEN"
      - name: Changing sed
        run: |
          echo "secrets are $COMPONENTS_GHA_JSON_TOKEN"
          echo $COMPONENTS_GHA_JSON_TOKEN
          echo "ahora sin bracket"
          echo ${{secrets.token}}
          FILEN=$file
          # remove carry return\eol\tab
          FILES="${FILEN//[$'\r\n\t']}" 
          echo "The json is : $FILES"
          go run main.go "-json=$FILES" -pr=$is_pr
