name: Send Information to Workflow

on:
  push:
    branches:
      - 'main'
    paths:
      - 'components-info/*.json'
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - 'main'
    paths:
      - 'components-info/*.json'

env:
  IS_PR: false
  IS_TRUE: true

jobs:
  get-json-files:
    runs-on: ubuntu-latest
    env:
      COMPONENTS_GHA_JSON_TOKEN: ${{secrets.COMPONENTS_GHA_JSON_TOKEN}}
      EVENT_CONTEXT: ${{ toJSON(github.event) }}
    outputs:
      json-data: ${{ steps.get-json-files.outputs.JSON_DATA }}
      misecretito: ${{ steps.devolvertoken.outputs.MI_TOKEN }}
      ispr: ${{ steps.determineworkflow.outputs.IS_PULLR }}
    steps:
      - name: imprimir contexto
        run: |
          echo $EVENT_CONTEXT
      - name: Checkout
        uses: actions/checkout@v3
        with:
            path: './'
      - name: determin_workflow
        id: determineworkflow
        if: github.event.pull_request && (github.event.action == 'opened' || github.event.action == 'synchronize')
        run: |
          echo "ghea:..."
          echo ${{ github.event.action }}
          echo $IS_PR
          echo $IS_TRUE
          echo "IS_PULLR=$IS_TRUE" >> $GITHUB_OUTPUT
          echo $IS_PULLR
      - name: Get JSON files
        id: get-json-files
        run: |
          echo "the secret is ..."
          echo $COMPONENTS_GHA_JSON_TOKEN
          echo "the secret with brackets is..."
          echo ${{secrets.COMPONENTS_GHA_JSON_TOKEN}}
          echo "MI_TOKEN=$COMPONENTS_GHA_JSON_TOKEN"
          cd './components-info'
          jq -s '.' *.json > joined.json
          echo "JSON_DATA=$(jq -c . < joined.json)" >> $GITHUB_OUTPUT
      - name: Devolver token si dios quiere
        id: devolvertoken
        run: echo "MI_TOKEN=$COMPONENTS_GHA_JSON_TOKEN" >> $GITHUB_OUTPUT
  call-workflow-passing-data:
    needs: get-json-files
    strategy:
      matrix:
        json: ${{ fromJson(needs.get-json-files.outputs.json-data) }}
    permissions:
      contents: read
      pull-requests: write
    uses: DCodingJLD/pruebawebhook1/.github/workflows/workflow-to-components.yml@main
    with:
      repo:  ${{ github.repository }}
      name:  ${{ matrix.json.name }}
      file:  ${{ toJSON(matrix.json) }}
      is_pr:  ${{ needs.get-json-files.outputs.ispr }}
    secrets:
      token: ${{secrets.COMPONENTS_GHA_JSON_TOKEN}}

